---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thoughts-backend-ingress
  namespace: example
spec:
  rules:
    # multiple services can be exposed on the same nodes, they get distinguished by their hostname
    - host: thoughts.example.local
      http:
        paths:
          - path: /pathtest
            pathType: Prefix
            backend:
              service:
                name: thoughts-service
                # make the service be exposed to the nodes on port 80
                port:
                  number: 80
